### ISSUE TITLE
[bug] some blocks generated it modded structures are unintentionally waterlogged

### ISSUE THREAD

**Issue by RyanCR03** [DomiIRL/FixedWaterlogging#2]
(example from mo' structures and repurposed structures)
![2021-12-23_10 52 03](https://user-images.githubusercontent.com/32957560/147271153-513b70df-5476-48ce-a148-d7c194bdb2b2.png)
![2021-12-23_11 07 54](https://user-images.githubusercontent.com/32957560/147272002-25185641-e1b7-4d2f-b50c-7181177e574a.png)

**Comment by DomiIRL** [comment]
gonna look into that thanks for reporting

**Comment by DomiIRL** [comment]
So I think I fixed it for all blocks now and uploaded it on curse ^^
