### ISSUE TITLE
client crashing at start

### ISSUE THREAD

**Issue by TheButterbrotMan** [DomiIRL/FixedWaterlogging#3]
My Modpack does crash on start, with waterlogging enabled.

https://www.curseforge.com/minecraft/modpacks/deathdusk

https://pastebin.com/4Z7DUt3N

**Comment by DomiIRL** [comment]
Which Mod version do you use?

**Comment by TheButterbrotMan** [comment]
1.0.1 for 1.18

**Comment by DomiIRL** [comment]
Can you try with 1.0.2?

**Comment by DomiIRL** [comment]
Ah I think I know whats the problem, one of the modded blocks inherits from a waterlogged block but overrides the properties.
I'll fix this tomorrow then

**Comment by Toilet-Lord** [comment]
Bump, I have the same problem, thanks for looking into it <3

**Comment by DomiIRL** [comment]
Everything should be fixed now you can update the mod
