### ISSUE TITLE
Random Crash While Exploring

### ISSUE THREAD

**Issue by Toilet-Lord** [DomiIRL/FixedWaterlogging#7]
Server crashes while exploring. I can't log back in bc the chunk loads in and makes the server crash

[crash-2022-01-18_02.19.35-server.txt](https://github.com/KxmischesDomi/FixedWaterlogging/files/7886961/crash-2022-01-18_02.19.35-server.txt)

**Comment by DomiIRL** [comment]
Can you try using this version? https://github.com/KxmischesDomi/FixedWaterlogging/actions/runs/1655433912
just click on artifacts and it‘ll download automatically

**Comment by Toilet-Lord** [comment]
lmao I think you did exactly what I thought I'd have done if I knew how to fix it myself (replacing the block with air)
The server crashes when the mod loads in, no need for me to get in the server now

I'm free all day if you wanna do more tests, thanks for looking into that <3

**Comment by Toilet-Lord** [comment]
here is the error the Server & Client gave me:

https://pastebin.com/tG1Mx0dU

**Comment by DomiIRL** [comment]
Since its an experimental mod and I'm currently not fixing any bugs I won't look into any issues rn.
Please don't use this mod for your regular survival worlds or anything it is really buggy and crashes with every other mod.
