### ISSUE TITLE
crash whenever activating pistons

### ISSUE THREAD

**Issue by Flame115** [DomiIRL/FixedWaterlogging#8]
whenever I use a piston game crashes

Crashlog: https://pastebin.com/GVMt0n30

**Comment by DarianLStephens** [comment]
Same issue here.

**Comment by liwiss** [comment]
Same here, I think it has to do with a compatibility error with the carpet mod.

**Comment by TurtNC** [comment]
A buddy of mine was having the same issue, after updating his graphic card drivers he has not had this crash, unfortunately, it has only been a day since he's updated them and we do not know for certain that's it's fixed

**Comment by DomiIRL** [comment]
Since its an experimental mod and I'm currently not fixing any bugs I won't look into any issues rn.
Please don't use this mod for your regular survival worlds or anything it is really buggy and crashes with every other mod.

**Comment by DarianLStephens** [comment]
I don't know about closing issues just because you aren't currently looking in to bugs. It makes it harder to keep track of things if you do decide to work on this again, and gives potential users the impression that these issues may have been fixed.
